export default {
  CREATE_PROJECT: 'CREATE_PROJECT',
  CREATE_PROJECT_ERROR: 'CREATE_PROJECT_ERROR',
  SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
  SIGNIN_ERROR: 'SIGNIN_ERROR',
  SIGNOUT_SUCCESS: 'SIGNOUT_SUCCESS',
  SIGNOUT_ERROR: 'SIGNOUT_ERROR',
};
